name: Deploy on dev.qfield.cloud
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy on dev.qfield.cloud
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: dev.qfield.cloud
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          envs: DEV_PASSWORD,REPO_TOKEN,REPO_USERNAME
          script_stop: true
          script: |
            cd /opt/qfieldcloud
            docker compose -f docker-compose.dev.yml stop
            echo "$DEV_PASSWORD" | sudo -S git pull https://"$REPO_USERNAME":"$REPO_TOKEN"@github.com/opengisch/qfieldcloud
            docker compose -f docker-compose.dev.yml up -d --build
            docker compose -f docker-compose.dev.yml exec -T web python manage.py collectstatic --no-input --clear
            docker compose -f docker-compose.dev.yml exec -T web python manage.py migrate --noinput

  status:
    name: Check dev.qfield.cloud status
    runs-on: ubuntu-22.04
    needs: deploy
    steps:
      - name: Check
        run: curl -f https://dev.qfield.cloud/api/v1/status/
