name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    runs-on: ubuntu-22.04
    name: Backport
    steps:
      - name: Backport
        uses: m-kuhn/backport@v1.2.5
        with:
          github_token: ${{ secrets.NYUKI_TOKEN }}
